apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
spec:
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      
      containers:
      - name: project1
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "600m"
        ports:
        - containerPort: 80
