name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dexterquazi/bankchimp .   
    - name: Docker Login
      run: docker login -u "${{secrets.DH_USERNAME}}" -p "${{secrets.DH_PASSWORD}}"
    - name: push
      run: docker push dexterquazi/bankchimp 
