name: JenkinsBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Jenkins-Action
      # You may pin to the exact commit or the version.
      # uses: joshlk/jenkins-githubaction@8ef510cf2dfb3affe8cbdfef1898b23c28847f39
      uses: joshlk/jenkins-githubaction@V0.0.1
      with:
        # Jenkins URL including http/https protocol
        url: https://cicd.mosque.digital
        # Jenkins job name to build
        job_name: test
        # Jenkins username
        username: admin
        # Jenkins API token
        api_token: 117cb281cab4ae3ed238f5027936c83174
        # Build parameters in JSON format e.g. `{"field1":"value1"}`
              
